### ISSUE TITLE
add libc_dbg! macro

### ISSUE THREAD

**Issue by adwhit** [mmastrac/rust-libc-print#17]
Hi, thanks for the crate, really useful.

I've mainly been using this crate for debugging in a `#![no_std]` context. I think t would be useful to have the [`dbg!`](https://doc.rust-lang.org/std/macro.dbg.html) macro available too.

**Comment by mmastrac** [comment]
Thanks for the feedback. Marking as "good first issue" as this should be reasonably easy to implement.

**Comment by SteveLauC** [comment]
Hi @mmastrac :)
 I made a PR for this issue:D
