### ISSUE TITLE
Suggestion for flushing stdout?

### ISSUE THREAD

**Issue by JOE1994** [mmastrac/rust-libc-print#7]
Hello, thank you for sharing this crate. :+1: 
`println!` macros in `std` don't immediately flush `stdout`, and therefore may need something like `std::io::stdout().flush().expect("error while flushing stdin");` to ensure immediate printing behavior.

Is there a recommended way to flush stdout while using this crate in `#![no_std]`? 
Thank you :smile:

**Comment by mmastrac** [comment]
Hi @JOE1994, I don't think you need to flush stdout as this uses write to write directly to the stdout file handle descriptor. If you find otherwise, let me know!
