### ISSUE TITLE
"attributes on expressions are experimental" when not used as a statement

### ISSUE THREAD

**Issue by nickmertin** [mmastrac/rust-libc-print#86]
Offending excerpt from my code:

```rust
use libc_print::std_name::*;

// ...

foo().unwrap_or_else(|err| eprintln!("error: {:?}", err));
```

My best guess is that there needs to be some added block level and/or semicolon to get the macro call to compile in all cases without needing `#![feature(stmt_expr_attributes)]`.

**Comment by mmastrac** [comment]
Published in v0.1.21
