### ISSUE TITLE
when i use it time , it tell link.exe error

### ISSUE THREAD

**Issue by ZhenYisp** [mmastrac/rust-libc-print#88]
linking with `link.exe` failed: exit code: 1120        
but i add .cargo/config.toml 
[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

so i want konw why?

**Comment by mmastrac** [comment]
I suspect what you're seeing here is a Windows issue where you're not linking against the C runtime. Unfortunately this library requires a `libc` of some sort at this time. A fix for #55 might be able to make this work, assuming you're able to provide a function that can write to stdout.
